### ISSUE TITLE
Use model for custom dataset

### ISSUE THREAD

**Issue by KfirdausMT** [AndrewSpano/Disentangled_Variational_Autoencoder#13]

**Comment by AndrewSpano** [comment]
Hello @KfirdausMT,

Thank you for your message. This project was not meant as a package/API, and thus the source code was not optimized to be fully parameterizable. It is possible to use the model on a custom dataset, but you will have to edit various parts of the code in order to adapt it to your dataset. One way to do it is:


1. Create a subclass for your dataset that inherits from the [VisionDataset](https://pytorch.org/vision/stable/_modules/torchvision/datasets/vision.html#VisionDataset) class. Make sure to implement the following methods:

    - `__init__()`
    - `__getitem__()`
    - `__len__()`
    
    To see an example, check [MNIST](https://pytorch.org/vision/stable/_modules/torchvision/datasets/mnist.html#MNIST).
  
2. Edit the `prepare_dataset()` function in the [utils.py](../blob/main/src/utils/utils.py) source file so that it returns a dictionary that describes the desired attributes for your dataset. Specifically,

    - The `'ds_method'` key should map to the subclass that represents your dataset.
    - The `'ds_shape'` key should map to the __common__ shape of the images in your dataset.
    - The `'ds_path'` should map to the root directory of your dataset.

<br>

These changes should work if you have a an __image dataset__. If your dataset contains data of some other kind, then apart from those changes, you will have to:

1. Define a subclass that inherits from the [Dataset](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#Dataset) class instead of VisionDataset. Again, you should implement the same methods as above.

2. The second step is the same as above, except that this time the `'ds_shape'` key should map to the __constant__ size of your data.

3. Change the [VAE](../blob/main/src/models/vae.py) class to implement another Neural Network architecture instead of 2D convolutions. It's up to you to choose the architecture, but make sure to edit any code that makes assumptions about the type of data, i.e. the `__init__()`, `_decode()`, `train_dataloader()`, `test_dataloader()`, `sample()`, `reconstruct()` methods.

**Comment by KfirdausMT** [comment]
Thanks for your explanation @AndrewSpano .. i got few further question.. 

1. Is this vision dataset able to cater for unlabeled image dataset?  
2. Is the CKPT file is the final latent vector value (like a weight file) that can be loaded in other DL model for further interpretation?

**Comment by AndrewSpano** [comment]
No problem @KfirdausMT. Regarding your other questions:

1. Yes, you don't need labeled data.
2. Not sure I understand your question, but if you want to save all or some weights of the model (including the mean/std layers), you can do it with pytorch. You may want to refer to [this](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

**Comment by KfirdausMT** [comment]
I tried my custom dataset with your suggestion. However, as my dataset is not in torchvision how can I call it in the "ds_method" in the uitls.py?

**Comment by AndrewSpano** [comment]
It should be your subclass, but __not__ instantiated. For example, if your class is

```python
from torchvision.datasets import VisionDataset

class MyCustomDataset(VisionDataset):

    def __init__(self, **kwargs):
        # your code here
```

Then you should use

```python
dataset_info['ds_method'] = MyCustomDataset  # do not create an object, just pass the class
```

Regarding what arguments you should use in the constructor (i.e. the `__init__()` method of your class), make sure to check the [`train_dataloader()`](https://github.com/AndrewSpano/Disentangled-Variational-Autoencoder/blob/main/src/models/vae.py#L203) and [`test_dataloader()`](https://github.com/AndrewSpano/Disentangled-Variational-Autoencoder/blob/main/src/models/vae.py#L241) methods in the [`VAE`](https://github.com/AndrewSpano/Disentangled-Variational-Autoencoder/blob/main/src/models/vae.py#L27) class, as this is where your subclass will be instantiated and used to train the VAE.
